# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ConfigureSnowflakeCLI@0
  inputs:
    configFilePath: './config.toml'
  displayName: SnowCliTest

- script: ls /home/vsts/.snowflake/
  displayName: 'Snowflake Directory Files'

- script: cat /home/vsts/.snowflake/config.toml
  displayName: 'Showing config content'

- script: snow --version
  displayName: 'Snow Version'

- script: snow connection test --debug
  displayName: 'Snow Version'
  env:
    SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: $(SNOWFLAKE_ACCOUNT)
    SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: $(SNOWFLAKE_PASSWORD)