default_connection_name = "mobilize" 
  
[connections] 
[connections.mobilize] 
account = "mobilize" 
user = "jovasquez" 
password = "Password2022." 
role = "SC_ASGARD_ROLE" 
warehouse = "SC_ASGARD_WH" 