name: Unit Testing for Snowflake CLI ADO extension
on: [push]
jobs:
  unit-test:
    name: Unit Test configure_snowflake_cli Task
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Unit Tests
      run: |
        cd tasks/configure_snowflake_cli
        export TASK_TEST_TRACE=1
        unset PIPX_BIN_DIR
        npm install -include=dev
        npm test

    - name: Show logs
      if: failure()
      run: |
        cd tasks/configure_snowflake_cli/tests/configureSnowflakeCliTest
        
        for LOG_FILE in *.log; do
            if [[ -e "$LOG_FILE" ]]; then
            echo "Contents of $LOG_FILE:"
            cat "$LOG_FILE"
            echo "---------------------------------"
            fi
        done